version: '3.9'

services:
  postgres:
    image: postgres:15.3-alpine
    container_name: app_store_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_store_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - app_network

  backend:
    build:
      context: ./application-store
      dockerfile: Dockerfile
    container_name: app_store_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/app_store_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  frontend:
    build:
      context: ./application-store-front
      dockerfile: Dockerfile
    container_name: app_store_frontend
    depends_on:
      - postgres
      - backend
    ports:
      - "4201:80"
    networks:
      - app_network

networks:
  app_network:

volumes:
  postgres-data:
